### ISSUE TITLE
Hey bro I have Questions this one think what i need

### ISSUE THREAD

**Issue by DragonfireHD** [SkylineMC/Mockingbird#12]
Can you me help on my server i have a Armor problem the Armor form Players dont save and i dont now how i fix this can you make Armorsave plugin in a perworldinventory style?

or can me help for this asked many people and developers please help me bro

**Comment by ethaniccc** [comment]
I'm sorry but I don't do plugin requests, if you want, you can ask in two places:
PMMP Forums: https://forums.pmmp.io/forums/requests/
PMMP Discord: https://discord.com/invite/bmSAZBG

**Comment by DragonfireHD** [comment]
Pls help me just look the Bug give maybe a Little Help

https://youtu.be/QPvUJsCOvOo

**Comment by ethaniccc** [comment]
Does the error occur without Mockingbird?

**Comment by DragonfireHD** [comment]
Yes but you plugin very nice but the Armor saving bug is a Big problem and i need for this please? can you not help on more last time?

**Comment by DragonfireHD** [comment]
I write all Developers and Pmmp but nothing respone i have no help for this 🥺😔

**Comment by ethaniccc** [comment]
If the issue is not related to Mockingbird, please refrain from making issues on this repository. You can try asking in the PMMP discord or the PocketMine forums like I had suggested earlier.

Also, I don't really do projects for certain people, so sorry - it must be one of your plugins that is causing this.
